// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: proto/sampleManager.proto

package go_sampleManager_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SampleMapping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClmSegments  []string `protobuf:"bytes,1,rep,name=clm_segments,json=clmSegments,proto3" json:"clm_segments,omitempty"`
	ItemId       string   `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	SampleItemId string   `protobuf:"bytes,3,opt,name=sample_item_id,json=sampleItemId,proto3" json:"sample_item_id,omitempty"`
}

func (x *SampleMapping) Reset() {
	*x = SampleMapping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sampleManager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SampleMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleMapping) ProtoMessage() {}

func (x *SampleMapping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sampleManager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleMapping.ProtoReflect.Descriptor instead.
func (*SampleMapping) Descriptor() ([]byte, []int) {
	return file_proto_sampleManager_proto_rawDescGZIP(), []int{0}
}

func (x *SampleMapping) GetClmSegments() []string {
	if x != nil {
		return x.ClmSegments
	}
	return nil
}

func (x *SampleMapping) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *SampleMapping) GetSampleItemId() string {
	if x != nil {
		return x.SampleItemId
	}
	return ""
}

type AddSampleMappingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AddSampleMappingResponse) Reset() {
	*x = AddSampleMappingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sampleManager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSampleMappingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSampleMappingResponse) ProtoMessage() {}

func (x *AddSampleMappingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sampleManager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSampleMappingResponse.ProtoReflect.Descriptor instead.
func (*AddSampleMappingResponse) Descriptor() ([]byte, []int) {
	return file_proto_sampleManager_proto_rawDescGZIP(), []int{1}
}

func (x *AddSampleMappingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddSampleMappingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FetchSampleItemIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClmSegments []string `protobuf:"bytes,1,rep,name=clm_segments,json=clmSegments,proto3" json:"clm_segments,omitempty"`
	ItemId      string   `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
}

func (x *FetchSampleItemIdRequest) Reset() {
	*x = FetchSampleItemIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sampleManager_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchSampleItemIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSampleItemIdRequest) ProtoMessage() {}

func (x *FetchSampleItemIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sampleManager_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSampleItemIdRequest.ProtoReflect.Descriptor instead.
func (*FetchSampleItemIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_sampleManager_proto_rawDescGZIP(), []int{2}
}

func (x *FetchSampleItemIdRequest) GetClmSegments() []string {
	if x != nil {
		return x.ClmSegments
	}
	return nil
}

func (x *FetchSampleItemIdRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type FetchSampleItemIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SampleItemId string `protobuf:"bytes,1,opt,name=sample_item_id,json=sampleItemId,proto3" json:"sample_item_id,omitempty"`
}

func (x *FetchSampleItemIdResponse) Reset() {
	*x = FetchSampleItemIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sampleManager_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchSampleItemIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSampleItemIdResponse) ProtoMessage() {}

func (x *FetchSampleItemIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sampleManager_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSampleItemIdResponse.ProtoReflect.Descriptor instead.
func (*FetchSampleItemIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_sampleManager_proto_rawDescGZIP(), []int{3}
}

func (x *FetchSampleItemIdResponse) GetSampleItemId() string {
	if x != nil {
		return x.SampleItemId
	}
	return ""
}

var File_proto_sampleManager_proto protoreflect.FileDescriptor

var file_proto_sampleManager_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x71, 0x0a, 0x0d, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6c, 0x6d, 0x5f, 0x73, 0x65, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6c, 0x6d, 0x53, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12,
	0x24, 0x0a, 0x0e, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x18, 0x41, 0x64, 0x64, 0x53, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x56, 0x0a, 0x18, 0x46, 0x65, 0x74, 0x63, 0x68, 0x53, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6c, 0x6d, 0x5f, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6c, 0x6d, 0x53, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0x41, 0x0a,
	0x19, 0x46, 0x65, 0x74, 0x63, 0x68, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x49, 0x74, 0x65, 0x6d,
	0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64,
	0x32, 0xbd, 0x01, 0x0a, 0x14, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x10, 0x41, 0x64, 0x64,
	0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x53,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x11, 0x46, 0x65, 0x74, 0x63, 0x68, 0x53,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x1f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x3f, 0x5a, 0x3d, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x3b, 0x67, 0x6f, 0x5f, 0x73,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_sampleManager_proto_rawDescOnce sync.Once
	file_proto_sampleManager_proto_rawDescData = file_proto_sampleManager_proto_rawDesc
)

func file_proto_sampleManager_proto_rawDescGZIP() []byte {
	file_proto_sampleManager_proto_rawDescOnce.Do(func() {
		file_proto_sampleManager_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_sampleManager_proto_rawDescData)
	})
	return file_proto_sampleManager_proto_rawDescData
}

var file_proto_sampleManager_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_sampleManager_proto_goTypes = []interface{}{
	(*SampleMapping)(nil),             // 0: proto.SampleMapping
	(*AddSampleMappingResponse)(nil),  // 1: proto.AddSampleMappingResponse
	(*FetchSampleItemIdRequest)(nil),  // 2: proto.FetchSampleItemIdRequest
	(*FetchSampleItemIdResponse)(nil), // 3: proto.FetchSampleItemIdResponse
}
var file_proto_sampleManager_proto_depIdxs = []int32{
	0, // 0: proto.SampleManagerService.AddSampleMapping:input_type -> proto.SampleMapping
	2, // 1: proto.SampleManagerService.FetchSampleItemId:input_type -> proto.FetchSampleItemIdRequest
	1, // 2: proto.SampleManagerService.AddSampleMapping:output_type -> proto.AddSampleMappingResponse
	3, // 3: proto.SampleManagerService.FetchSampleItemId:output_type -> proto.FetchSampleItemIdResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sampleManager_proto_init() }
func file_proto_sampleManager_proto_init() {
	if File_proto_sampleManager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_sampleManager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SampleMapping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sampleManager_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSampleMappingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sampleManager_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchSampleItemIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sampleManager_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchSampleItemIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_sampleManager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sampleManager_proto_goTypes,
		DependencyIndexes: file_proto_sampleManager_proto_depIdxs,
		MessageInfos:      file_proto_sampleManager_proto_msgTypes,
	}.Build()
	File_proto_sampleManager_proto = out.File
	file_proto_sampleManager_proto_rawDesc = nil
	file_proto_sampleManager_proto_goTypes = nil
	file_proto_sampleManager_proto_depIdxs = nil
}
